### ISSUE TITLE
the image of 6.2.5 has log file

### ISSUE THREAD

**Issue by wyy0117** [liferay/liferay-docker#15]
I pull the image of 6.2.5,and run it with `docker run -itd --name liferay6.2 -p 8080:8080  -v ~/docker/data/liferay6.2:/etc/liferay/mount liferay/portal:6.2.5-ga6`,I can't init liferay successful，and it hit 
"This instance is inactive. Please contact the administrator.",I get into the container,and find a log file "liferay.2019-02-22.log" in /opt/liferay/logs folder,please delete it and rebuild.
thx.

**Comment by wyy0117** [comment]
I find it is update today,I pull the lasted image,It still has the same problem, a log file of "liferay.2019-03-13.log".

**Comment by zsoltbalogh** [comment]
The cleanup change was merged in, this problem should be resolved at the next full publish.

**Comment by zsoltbalogh** [comment]
@wyy0117, thank you for reporting this!

**Comment by wyy0117** [comment]
today,I pulled the version of liferay/portal:6.2.5-ga6 and run it.But there still have a log file in /opt/liferay/logs named liferay.2018-11-03.log.

**Comment by zsoltbalogh** [comment]
You are correct @wyy0117 , we'll need to investigate why this happens. I'll reopen this ticket.

**Comment by zsoltbalogh** [comment]
I've checked the issue again today and it was related to a warmup issue most probably. Previously we only gave 10 seconds for tomcat to shut down before we deleted the files and it was not enough. Now there are changes in the warmup code which ensure we shut down the warmup process so these files shouldn't stay there. We'll to a full publish of images in the next weeks, the issue should be fixed (based on local tests) by then.
